### ISSUE TITLE
Mirror / copy Baloise internal pipeline to github for code review

### ISSUE THREAD

**Issue by culmat** [baloise/CICD-pipeline#11]
https://github.com/baloise/jenkins-shared-library-archive

**Comment by joachimprinzbach** [comment]
we could just copy it to the private repo?

**Comment by culmat** [comment]
made a copy

**Comment by culmat** [comment]
add also the other library with jboss_rollout

**Comment by culmat** [comment]
also copied https://github.com/baloise/WorkflowLibs-archive
