### ISSUE TITLE
What is the license / data classification of the MyCloud API

### ISSUE THREAD

**Issue by culmat** [baloise/CICD-pipeline#15]
the pipeline code is Apache 2 for now.
Can we keep the library open source when at some point we will call the MyCloud API?
( this will reveal the API design / not its implementation)

**Comment by bhaskarchenchu** [comment]
@culmat ,   Data classification is confidential  for MyCloud API implementation. This specific case is limited to access API from the pipeline, okay to keep the Library Opensource and call MyCloud API.
