### ISSUE TITLE
Expose Web UIs & APIs via HTTPS on public internet ( DNS )

### ISSUE THREAD

**Issue by culmat** [baloise/CICD-pipeline#16]

**Comment by culmat** [comment]
see https://github.com/baloise/CICD-pipeline/wiki/Lab-Environment#user-content-public-urls-info

**Comment by culmat** [comment]
can we plz also expose mycloud UI & API?

**Comment by bhaskarchenchu** [comment]
Provisioned DNS entries for # 

1) Jenkins, Nexus & APP Server Endpoints# https://github.com/baloise/CICD-pipeline/wiki/Lab-Environment#public-urls-info

2) Working on exposing  MyCloud APIs through secure SSL &  SSH to Postgresql.  ETA-  25th-Nov-2020.

**Comment by bhaskarchenchu** [comment]
Exposed WebUI & APIs of Mycloud though Public DNS. Details are shared through Email.
