### ISSUE TITLE
Add Maven Build function to jenkins-shared-library

### ISSUE THREAD

**Issue by niiku** [baloise/CICD-pipeline#21]
* Build maven (relying on existing mavenBuild api)
* Run build in container and copy artifacts (verify if feasible)

**Comment by culmat** [comment]
Hi @bhaskarchenchu,
can you please install docker on the jenkins, so that https://jenkinsbaloise.hclcnlabs.com/job/docker/ runs?
Thx
Matthias

**Comment by bhaskarchenchu** [comment]
Hi @culmat ,
Thanks for notifying.  Docker installed @Jenkins and ran test pipeline could see it's working.  Please validate.

**Comment by culmat** [comment]
very nice. thx

**Comment by culmat** [comment]
https://jenkinsbaloise.hclcnlabs.com/job/corellia/job/feat%252FMaven/
