### ISSUE TITLE
Document interaction and interfaces between CI/CD Pipelines and Shop API

### ISSUE THREAD

**Issue by danielgrob** [baloise/CICD-pipeline#26]
List components:
- ValueMation
- Orchestra
- MyCloud
- JIRA
- ...

Describe access to those components from CI/CD pipelines.

Describe workflow from CI/CD pipelines perspective.

**Comment by matal0** [comment]
Functional overview of the lab env is available here: https://confluence.baloisenet.com/atlassian/x/fQO7fQ
Implementation is still in progress and might lead to adjustments on component list and their interaction.

Components (tools) to be set up or already available:
- Shop (Valumation)
- Process Engine (Valuemation)
- Interfaces Process Engine-myCloud/User (Orchestra)
- Deployment Engine (myCloud)
- CMDB/SMDB (Valuemation)
- provider catalog DB
- artifact store, code repo, cfg repo (github, Liima)
- job scheduler (Jenkins)

Access from pipelines: tbd once implementation in Valuemation starts
Workflow from pipeline view: tbd, trigger of Order Compilation Subprocess of MVP https://confluence.baloisenet.com/atlassian/x/T5Kxf
