### ISSUE TITLE
Destroy JBoss server

### ISSUE THREAD

**Issue by danielgrob** [baloise/CICD-pipeline#31]

**Comment by culmat** [comment]
Destroy call ready to be tested

**Comment by culmat** [comment]
request No 102/103 with ProvisionRequestDate = 2020-12-21T16:00:49.170/2020-12-22T07:26:25.170 for IP 172.16.5.64/172.16.5.65 are still "Fulfilment In-Progress"
trying to request another delete Action for 172.16.5.64 I get the following error message

{
    "Result": null,
    "ErrorMessage": null,
    "Status": "Fail",
    "Message": "Same action request with SRREQ000102 already pending. Request can be placed after completion of previous pending request."
}

**Comment by culmat** [comment]
Round trip working through API
