### ISSUE TITLE
Create JBoss server

### ISSUE THREAD

**Issue by danielgrob** [baloise/CICD-pipeline#32]

**Comment by renat1sakenov** [comment]
For JBoss configuration provisioning, the internal Liima instance could be used - a new runtime "hcllab_jboss" has been created for this purpose.

The process of providing Liima configuration (standalone-ha.xml /  Java parameters and more), works by:
- Running a Liima deployment which created the configuration
- Pushing the resources into a Git Repository (and in parallel executing different tasks on the host itself)
  - Where will our repository reside? On Github?
  - The other tasks which run directly on the host do not need to be executed immediately, but it will be necessary to trigger an ansible playbook from Jenkins after git-push OR run the playbook when the rollout starts.
- Rollout: Done by Jenkins. Checking out the Git-Repository, Creating the configuration locally.
  - This will require the rollout component of the current WorkflowLibs.

**Comment by culmat** [comment]
see https://jenkinsbaloise.hclcnlabs.com/view/testpipelines/job/011-mycloudapi-jb-vmprovision/
