### ISSUE TITLE
Decision on MyCloudAPI Provisioning workflows

### ISSUE THREAD

**Issue by bhaskarchenchu** [baloise/CICD-pipeline#38]
No of workflows can made available through mycloudapi.   At present ,  2 tier VM provision workflow enabled.  
**Following workflow can enable#**
1. Single Linux VM  Provision(Plain)
2. Single  JBOSS VM Provision 
3. Single PostgreSQL VM Provision
4.  2 Tier VM provision (1-Postgresql & 1- JBOSS) -(Already available)

Decision need to be made, whether any requirement for additional workflow ?

**Comment by culmat** [comment]
I would opt for rather low level components in MyCloud ( single server, or even plain linux ). The teams can then manage the configuration of the higher level components in git.

@matal0, @vangual, @niiku, @joachimprinzbach what do you think?

**Comment by matal0** [comment]
The proposed workflows are sufficient from my point of view. I agree with culmat that low level components are prefered.

**Comment by vangual** [comment]
I agree with the preference of consuming smaller lower-level workflows. But currently they're online presented as a somewhat higherlevel workflow that makes quite a few decisions and executions behind the scenes automatically.. It needs careful drawing of the split line what we consider on the mycloud-side and what not. 

As an example currently the flows take the specified "Metal-Type" (Bronze, Gold, etc.) and run thru some pre-defined logic to figure out if they need to create one or multiple machines, maybe even another loadbalancer infront, connects their cluster-configs/ips, and decides how to name these machines according to their jobs (infra, app, db, etc). 

Taking advantage of this feature or denying it adjusts the "lowlevel-line" (if we can even call it a straight line at this point.) as it affects how much config has to be supplied on our side and how the config has to be delivered to a cluster. 

The main benefit of the existing "rich" workflow I see is that it takes care of some of the lowlevel configuration stuff (like defining the cluster itself) they may never be interesting to manipulate/specify for us.
On the downside, it takes away precision-control on our side. We don't store in git what's behind the "Gold" spec, as that would be decided by an invisible workflow on the mycloud side.

EDIT: personal conclusion: As much as I like to have laser-like precision control over everything, I'm leaning to using the existing level and calling those "lowlevel" in the interest of having something to deliver sooner than later.
