### ISSUE TITLE
Allow querying provisioning status

### ISSUE THREAD

**Issue by niiku** [baloise/CICD-pipeline#39]
During the provisioning of a virtual machine, jboss server, postgres instance we need to be able to query the provisioning status (in progress, failed, finished).

We need an example how the status can be queried after the initial provisioning request.

**Comment by bhaskarchenchu** [comment]
New API with details provisioned last week does exactly what is expected#

https://mycloudbaloise.hclcnlabs.com/webapi/Requests/RequestDetails/OrgEntityID/ORG-xxxxxxx/PlatformEntityID/VMWAR-xxxxxxx-1CF83A8A6237/RequestNo/{RequestNO_Value}/RequestDetailId/-1 .

Please check for more details @https://github.com/baloise/CICD-pipeline-private/blob/main/private/Baloise-Lab-MycloudAPI_V1.0.xlsx

**Comment by bhaskarchenchu** [comment]
Please find the comments for more details.
