### ISSUE TITLE
Establish AS IS tool stack

### ISSUE THREAD

**Issue by culmat** [baloise/CICD-pipeline#5]
- AS IS
- TO BE

https://github.com/baloise/CICD-pipeline/wiki/Tool-stack

**Comment by culmat** [comment]
**How do we take design decisions?**
* fist to five?
* pull request comments?
* documentation in doc folder or Wiki?

**First step: version control**

**Comment by MarkusTiede** [comment]
Documentation in doc folder - why: https://about.gitlab.com/handbook/handbook-usage/#wiki-handbooks-dont-scale

**Comment by culmat** [comment]
maybe we will also need orchestra
