### ISSUE TITLE
Integrated Testing of Lab Environment

### ISSUE THREAD

**Issue by culmat** [baloise/CICD-pipeline#9]
Test integration of all Components and Workflow

**Comment by culmat** [comment]
Hello @bhaskarchenchu,
I need to register a shared library.
Can plz give the baloise admin user permissions?
Thx & CU
Matthias

![image](https://user-images.githubusercontent.com/638519/98573260-813c7480-226b-11eb-89b3-a7aa2d870add.png)

**Comment by culmat** [comment]
the library should be called **sharedlib** have **main** as default branch ( will be changed to **release** later) and have this repo as source ( https://github.com/baloise/CICD-pipeline.git)

**Comment by Solaflex** [comment]
@culmat Is the MyCloud portal accessible through the internet now? If yes, could you share the login credentials with me? I was unable to find them in the private wiki

**Comment by bhaskar-chenchu** [comment]
@culmat , baloiseadmin have admin permissions now.

**Comment by culmat** [comment]
thx for the admin rights. Could create the library & successful build

**Comment by bhaskar-chenchu** [comment]
sounds cool.
